In [15]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso

from spe.mse_estimator import ErrorComparer

In [2]:
err_cmp = ErrorComparer()

In [3]:
(test_err,
 test_err_alpha,
 cb_err,
 cbiso_err) = err_cmp.compareIID(model=Lasso(alpha=0.31))

In [4]:
test_err.mean(), test_err_alpha.mean(), cb_err.mean(), cbiso_err.mean()

(0.3429022052570812,
 0.3289096114478815,
 0.30241720705147124,
 0.2975638962356867)

In [7]:
(test_err_200,
 test_err_alpha_200,
 cb_err_200,
 cbiso_err_200) = err_cmp.compareIID(niter=200, model=Lasso(alpha=0.31))

In [8]:
test_err_200.mean(), test_err_alpha_200.mean(), cb_err_200.mean(), cbiso_err_200.mean()

(0.5548475010658325,
 0.5762377285901351,
 0.5865199981898709,
 0.5580155016374233)

In [19]:
alphas = [0.05, 0.1, 0.2, 0.5, 0.8, 1.]
na = len(alphas)
niter = 100

test_err = np.zeros((na, niter))
test_err_alpha = np.zeros((na, niter))
cb_err = np.zeros((na, niter))
cbiso_err = np.zeros((na, niter))

for i,alpha in enumerate(alphas):
    print(i)
    (test_err[i,:],
     test_err_alpha[i,:],
     cb_err[i,:],
     cbiso_err[i,:]) = err_cmp.compareIID(model=Lasso(alpha=0.31),
                                          alpha=alpha)
    

0
1
2
3
4
5


In [20]:
risk = test_err.mean(axis=1)
risk_alpha = test_err_alpha.mean(axis=1)
risk_cb = cb_err.mean(axis=1)
risk_cbiso = cbiso_err.mean(axis=1)
risk, risk_alpha, risk_cb, risk_cbiso

(array([0.70777805, 0.76247479, 0.80678709, 0.29557861, 0.40138645,
        0.78577594]),
 array([0.67875766, 0.78511074, 1.04449846, 0.52522517, 0.53452883,
        1.46902004]),
 array([0.70776465, 0.76100605, 0.94316857, 0.42678149, 0.52253926,
        1.44320546]),
 array([0.71255507, 0.73951555, 0.89475952, 0.42081206, 0.5260177 ,
        1.45102804]))